services:
  mysql:
    restart: 'always'
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Bn5W}71-b0~(
      MYSQL_DATABASE: sgfcarlos
      MYSQL_USER: carlos
      MYSQL_PASSWORD: carlos
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    restart: 'always'
    image: yuyu09/sos24repository:sgfcarlos
    container_name: laravel_app
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - app-data:/var/www

networks:
  app-network:

volumes:
  app-data:
    driver: local 
  mysql-data:
    driver: local 